name: Build Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_NDK_ROOT: ${{ github.workspace }}/android-ndk

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Android SDK & NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip openjdk-17-jdk wget
          mkdir -p $ANDROID_SDK_ROOT
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          mv $ANDROID_SDK_ROOT/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: Setup Haxelib and Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp
          haxelib install hxpkg --global
          haxelib run hxpkg setup --global
          hxpkg install
          # Android-specific libs
          haxelib git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools.git
          haxelib git extension-videoview https://github.com/MaysLastPlay77/extension-videoview.git
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git

      - name: Compile hxcpp for Android
        run: |
          cd ~/haxelib/hxcpp/git/tools/run
          haxe compile.hxml
          cd ..
          cd ./hxcpp
          haxe compile.hxml
          cd ../..

      - name: Build Android APK
        run: |
          lime build android -final -Dandroid -Drelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: export/android/release/bin/*.apk