name: Build Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
      # Checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Instalar Haxe
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      # Instalar dependências do sistema
      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y unzip wget openjdk-17-jdk

      # Instalar Android SDK + NDK corretamente
      - name: Install Android SDK & NDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdtools.zip
          unzip -q cmdtools.zip -d $ANDROID_SDK_ROOT/cmdline-tools

          # Aceitar licenças
          yes | $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

          # Instalar plataformas necessárias
          yes | $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653"

      # Configurar haxelib + libs do projeto
      - name: Setup Haxelib and Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp
          haxelib install hxpkg --global
          haxelib run hxpkg setup --global
          hxpkg install

          # libs Android do Psych Engine
          haxelib git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools.git
          haxelib git extension-videoview https://github.com/MaysLastPlay77/extension-videoview.git
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git

      # Compilar hxcpp
      - name: Compile hxcpp
        run: |
          cd ~/haxelib/hxcpp/git/tools/run
          haxe compile.hxml
          cd ..
          cd ./hxcpp
          haxe compile.hxml
          cd ../..

      # Build APK release
      - name: Build Android APK
        run: |
          haxelib run lime build android -final -Dandroid -Drelease

      # Upload do APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: export/android/release/bin/*.apk